### ISSUE TITLE
Use only one KV-Store for both Win and Unix

### ISSUE THREAD

**Issue by stefan-kolb** [stefan-kolb/nucleus#65]
Any replacements can be configured as long as they can be used via the `moneta` interface.

**Comment by stefan-kolb** [comment]
@croeck Any rationale why we don't only use LMDB as default?

**Comment by croeck** [comment]
Nothing important I guess. As you probably know I started with `Daybreak` and used `LMDB` as fallback on windows. `LMDB` should be somewhat slower, but still fast enough for our purpose :smiley:
